version: '3.8'

services:
  web:
    restart: always
    container_name: web
    build: .
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    image: app:djnago
    environment:
      - "DJANGO_SECRET_KEY=t8wrj!=x&em6+x%z1_!m6n8m3$$jis8!wkhxzn##!_(-%-u9t2t"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
      - USE_S3=false

  db:
    image: postgres:14
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=ecommerce
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  esearch:
    container_name: esearch
    image: elasticsearch:7.14.2
    environment:
      - cluster.name=ecommerce-elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    depends_on:
      - db

  redis:
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    container_name: celery_ecommerce
    restart: always
    build:
      context: .
    command: celery -A ecommerce worker -l info
    environment:
      - DEGUB=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379:0
    depends_on:
      - redis
    volumes:
      - .:usr/src/app
  # celery-beat:
  #   container_name: celery_beat_ecommerce
  #   restart: always
  #   build:
  #     context: .
  #   command: celery -A ecommerce beat -l info
  #   depends_on:
  #     - redis
  #     - celery
  #   volumes:
  #     - .:usr/src/app
  # flower:
  #   container_name: flower_ecommerce
  #   image: mher/flower
  #   environment:
  #     - CELERY_BROCKER_URL=redis://redis:6379/0
  #   ports:
  #     - "8888:8888"

volumes:
  postgres_data:
  esearch:
