# Generated by Django 4.0.2 on 2022-04-03 10:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='is_on_sale',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='sale_price',
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'the price must be between 0 and 999.99.'}}, help_text='format: maximum price 999.99', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('250'))], verbose_name='recommended retail price'),
        ),
    ]
