# Generated by Django 4.0.2 on 2022-02-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20220220_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('SH', 'Self-help'), ('N', 'Novel'), ('F', 'Fiction')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1, null=True),
        ),
    ]
