# Generated by Django 4.0.2 on 2022-02-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_category_book_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
