# Generated by Django 4.0.2 on 2022-02-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
    ]
