# Generated by Django 4.0.2 on 2022-03-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_book_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')], 'verbose_name_plural': 'items'},
        ),
    ]
