# Generated by Django 4.0.2 on 2022-03-05 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-title'], 'permissions': [('special_status', 'Can read all books')], 'verbose_name_plural': 'items'},
        ),
    ]
