# Generated by Django 4.0.2 on 2022-03-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
