# Generated by Django 4.0.2 on 2022-02-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='title',
        ),
    ]
