# Generated by Django 4.0.2 on 2022-03-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_invoice_address_invoice_address_2_invoice_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.CharField(choices=[('B', 'البصرة')], max_length=2, null=True),
        ),
    ]
