# Generated by Django 4.0.2 on 2022-03-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_invoice_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
