# Generated by Django 4.0.2 on 2022-03-02 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_order_address_order_address_2_order_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
